# Generated by Django 5.2.6 on 2025-09-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='respondent_identifier',
            field=models.CharField(blank=True, help_text='Идентификатор респондента (Telegram ID, UUID, email и т.д.)', max_length=255),
        ),
    ]
